In [14]:
import numpy as np
import pandas as pd

I am using a dataset where zeros are missing data.

In [15]:
df = pd.read_csv('diabetes.csv')
y = df.iloc[0:767,8].values
X = df.iloc[0:767,0:7].values
pd.set_option("display.max_rows", 20, "display.max_columns", None)
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [16]:
df.loc[df["Glucose"] == 0.0 , "Glucose"] = np.nan
df.loc[df["BloodPressure"] == 0.0 , "BloodPressure"] = np.nan
df.loc[df["SkinThickness"] == 0.0 , "SkinThickness"] = np.nan
df.loc[df["Insulin"] == 0.0 , "Insulin"] = np.nan
df.loc[df["BMI"] == 0.0 , "BMI"] = np.nan
df.isnull().sum()[1:6]

Glucose            5
BloodPressure     35
SkinThickness    227
Insulin          374
BMI               11
dtype: int64

test 1: I want to remove features SkinThikness and insulin and impute others

In [24]:
df1 = df.drop(['Insulin' , 'SkinThickness'] , axis=1)
df1
df1.isnull().sum()[1:4]

Glucose           5
BloodPressure    35
BMI              11
dtype: int64

In [25]:
df1

,Pregnancies,Glucose,BloodPressure,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,33.6,0.627,50,1
1,1,85.0,66.0,26.6,0.351,31,0
2,8,183.0,64.0,23.3,0.672,32,1
3,1,89.0,66.0,28.1,0.167,21,0
4,0,137.0,40.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...
763,10,101.0,76.0,32.9,0.171,63,0
764,2,122.0,70.0,36.8,0.340,27,0
765,5,121.0,72.0,26.2,0.245,30,0
766,1,126.0,60.0,30.1,0.349,47,1
767,1,93.0,70.0,30.4,0.315,23,0

In [29]:
from sklearn.impute import KNNImputer
nan = np.nan
y1 = df.iloc[0:767,6].values
X2 = df.iloc[0:767,0:5].values
imputer = KNNImputer(n_neighbors=7, weights="uniform")
x_imputed = imputer.fit_transform(X2)

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train , y_test = train_test_split(x_imputed , y , test_size = 0.2 , random_state=1 , stratify = y)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
sc.fit(X_test)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [37]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(criterion='gini', n_estimators=5000, 
    random_state=1, n_jobs=2 , max_depth=3)
forest.fit(X_train_std , y_train)
'''y_pred_forest = forest.predict(X_train_std)
y_pred_forest_test = forest.predict(X_test_std)

print(accuracy_score(y_test , y_pred_forest_test))
print(accuracy_score(y_train , y_pred_forest))'''

'y_pred_forest = forest.predict(X_train_std)\ny_pred_forest_test = forest.predict(X_test_std)\n\nprint(accuracy_score(y_test , y_pred_forest_test))\nprint(accuracy_score(y_train , y_pred_forest))'